"""
Memory Index Regeneration

Generates MEMORY.md index from all memory files in the memory directory.
The index is automatically loaded by Claude Code at session start.
"""

import os
import re
import yaml
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple


def get_memory_dir() -> Path:
    """Get the memory directory path."""
    memory_dir = os.environ.get("MEMORY_DIR", "~/.claude/memory")
    if memory_dir == "~/.claude/memory":
        memory_dir = str(Path.home() / ".claude" / "memory")
    return Path(memory_dir).expanduser()


def get_max_lines() -> int:
    """Get maximum lines for the index."""
    return int(os.environ.get("MEMORY_INDEX_MAX_LINES", "150"))


def parse_frontmatter(file_path: Path) -> Dict:
    """
    Extract YAML frontmatter from markdown file.

    Args:
        file_path: Path to markdown file

    Returns:
        Parsed frontmatter as dict, empty if none found.
    """
    try:
        with open(file_path, encoding="utf-8") as f:
            content = f.read()

        # Match YAML frontmatter between --- delimiters
        match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if match:
            return yaml.safe_load(match.group(1)) or {}
    except Exception:
        pass

    return {}


def categorize_memories(memory_dir: Path) -> Dict[str, List[Dict]]:
    """
    Categorize memories by type.

    Args:
        memory_dir: Path to memory directory

    Returns:
        Dict mapping types to list of memory entries.
    """
    categorized = {
        "user": [],
        "feedback": [],
        "project": [],
        "reference": [],
        "other": [],
    }

    if not memory_dir.exists():
        return categorized

    for md_file in sorted(memory_dir.glob("*.md")):
        # Skip the index itself
        if md_file.name == "MEMORY.md":
            continue

        meta = parse_frontmatter(md_file)

        if not meta or "name" not in meta:
            continue

        memory_type = meta.get("type", "other")
        if memory_type not in categorized:
            memory_type = "other"

        categorized[memory_type].append({
            "file": md_file.name,
            "name": meta["name"],
            "description": meta.get("description", "")[:100],
            "scope": meta.get("scope", ""),
            "updated_at": meta.get("updated_at", ""),
        })

    return categorized


def format_category(category: str, memories: List[Dict]) -> str:
    """
    Format a category section for the index.

    Args:
        category: Category name
        memories: List of memory entries

    Returns:
        Formatted markdown section.
    """
    if not memories:
        return ""

    lines = [f"\n## {category.capitalize()}\n"]

    for mem in memories:
        desc = mem["description"]
        if desc:
            lines.append(f"- [{mem['name']}]({mem['file']}) — {desc}")
        else:
            lines.append(f"- [{mem['name']}]({mem['file']})")

    return "\n".join(lines)


def generate_index() -> Tuple[str, int]:
    """
    Generate MEMORY.md from all memory files.

    Returns:
        Tuple of (index content, total memory count)
    """
    memory_dir = get_memory_dir()
    max_lines = get_max_lines()

    # Create directory if not exists
    memory_dir.mkdir(parents=True, exist_ok=True)

    # Categorize memories
    categorized = categorize_memories(memory_dir)

    # Count total memories
    total_count = sum(len(mems) for mems in categorized.values())

    # Build index content
    lines = [
        "# Memory Index",
        "",
        "> Generated by AgentBrain. Do not edit manually.",
        f"> Last updated: {datetime.now().isoformat()}",
        f"> Total memories: {total_count}",
    ]

    # Add sections (in priority order)
    order = ["user", "feedback", "project", "reference", "other"]
    for category in order:
        section = format_category(category, categorized[category])
        if section:
            lines.append(section)

    # Join and truncate if needed
    content = "\n".join(lines)

    # Simple line-based truncation
    content_lines = content.split("\n")
    if len(content_lines) > max_lines:
        content_lines = content_lines[:max_lines]
        content_lines.append("\n... (index truncated)")
        content = "\n".join(content_lines)

    return content, total_count


def write_index(content: str) -> Path:
    """
    Write index to MEMORY.md.

    Args:
        content: Index content to write

    Returns:
        Path to written file.
    """
    memory_dir = get_memory_dir()
    index_file = memory_dir / "MEMORY.md"

    index_file.write_text(content, encoding="utf-8")

    return index_file


def main():
    """Main entry point."""
    content, count = generate_index()
    index_path = write_index(content)

    print(f"Generated memory index: {index_path}")
    print(f"Total memories indexed: {count}")

    return index_path, count


if __name__ == "__main__":
    main()
